services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Sioweb\LinkedElementBundle\:
        resource: '../src/'
        exclude: '../src/{DependencyInjection}'
